### ISSUE TITLE
Project might want a license.

### ISSUE THREAD

**Issue by jimstudt** [alcover/buffet#1]
Most other people are unable to lawfully use your code without a license. If your intent is to allow use, then you should add a license. This is mechanically trivial following the [Github instructions](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

Selecting a license is of course nontrivial. My personal choice when I intend unlimited use is the MIT license and as a consumer of licenses it is one that makes no barriers.

**Comment by Kaffeebohne** [comment]
The problem with MIT is that each use and fork has to take all the previous License headers and add the own reference.
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

If you even want to avoid this you can check the BSD0-clause. You can copy it from one of [Rob Landley](https://github.com/landley)'s repos.
Basically allows the same but without the need to copy previous licenses.

**Comment by Qix-** [comment]
No it doesn't. You can put MIT in the root of the repository and it's fine. You can also automate the header thing if you want to install them systemwide.

**Comment by Kaffeebohne** [comment]
@Qix- thanks for that insight.

**Comment by alcover** [comment]
Done, thx.

**Comment by Qix-** [comment]
Meh. GPL3 makes it difficult to use this in most cases. Thank you either way, though.
